var firstname = 'Renato';
var lastname = 'Morales';
var age = '39';
var dateofbirth = '10/10/1978';
var address = '223 Olive St';
console.log ('Name: ' , firstname);
console.log('Lastname: ' , lastname);
console.log('Age' , age);
console.log('BirthDate: ' , dateofbirth);
console.log('Address:' , address);