let num1 = 9;
let num2 = 1;
console.log(num2, " times ", num1, ' equals ', num1*num2);
num2 ++;
console.log(num2, " times ", num1, ' equals ', num1*num2);
num2 ++;
console.log(num2, " times ", num1, ' equals ', num1*num2);
num2 ++;
console.log(num2, " times ", num1, ' equals ', num1*num2);
num2 ++;
console.log(num2, " times ", num1, ' equals ', num1*num2);
num2 ++;
console.log(num2, " times ", num1, ' equals ', num1*num2);
num2 ++;
console.log(num2, " times ", num1, ' equals ', num1*num2);
num2 ++;
console.log(num2, " times ", num1, ' equals ', num1*num2);
num2 ++;
console.log(num2, " times ", num1, ' equals ', num1*num2);
num2 ++;
console.log(num2, " times ", num1, ' equals ', num1*num2);
num2 ++;